# Generated by Django 4.1.3 on 2022-12-17 22:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('venueName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=300)),
                ('capacity', models.IntegerField()),
                ('attendees', models.IntegerField(default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
